services:
  nginx-web:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    restart: always
    volumes:
      - ./web/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web/nginx/certs:/etc/nginx/certs:ro

  web:
    image: ${WEB_IMAGE}
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: ${DB_IMAGE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: