name: Pull Request Orchestrator
run-name: "${{ github.workflow }}"

on:
  pull_request:
    branches: [ staging, dev, pipeline-test ]

permissions:
  contents: read
  packages: write

jobs:
  ci:
    name: 1 - Continuous Integration
    uses: ./.github/workflows/1-integration.yml
    secrets: inherit

  build_push:
    name: 2 - Continuous Integration - Push
    needs: ci
    uses: ./.github/workflows/2-integration-push.yml
    secrets: inherit

  delivery:
    name: 3 - Continuous Delivery
    needs: build_push
    uses: ./.github/workflows/3-delivery.yml
    with:
      image_tag: ${{ github.sha }}
    secrets: inherit