name: Pull Request Orchestrator
run-name: "${{ github.workflow }}"

on:
  pull_request:
    branches: [ main, dev ]

permissions:
  contents: read
  packages: write

jobs:
  ci:
    name: 1 - Continuous Integration
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    
  cd:
    name: 2 - Continuous Delivery
    needs: ci
    uses: ./.github/workflows/cd.yml
    with:
      image_tag: ${{ github.sha }}
    secrets: inherit

  deploy:
    name: 3 - Continuous Deployment
    if: github.base_ref == 'main'
    needs: cd
    uses: ./.github/workflows/deploy.yml
    with:
      image_tag: ${{ github.sha }}
    secrets: inherit