name: Pull Request Orchestrator
run-name: "${{ github.workflow }}"

on:
    pull_request:
        branches: [ staging, dev, pipeline-test ]

permissions:
  contents: read
  packages: write

jobs:
  ci:
    name: 1 - Continuous Integration
    uses: ./.github/workflows/ci.yml
    secrets: inherit
  cd:
    name: 3 - Continuous Delivery
    needs: ci
    uses: ./.github/workflows/cd.yml
    with:
      image_tag: ${{ github.sha }}
    secrets: inherit